arch: amd64
os: linux
dist: bionic

language: node_js

node_js:
  - 14

env:
  global:
    - secure: pD4HIPWOoHbeEFdrpgg/tWmPiT6nLfX+uB8FsFICYZu1FajvYcFHRStLtOfShZ2QaLF/fCvqZFe6dvEYZ3ju+O6pSm0lXcd7nFqji6OjgMnVEr1CDiWk0yiFxC0aflcU7wT1OLutMgdNEF/9+r2JJOKuhxzG7GOMtOp5P/CSW6kEkfUe/dFxRvdRwjSj1FvQP2IToqD/PkzEyyJw/oi7PyVzl0+gYGbRsZMA0vGlrawE37S3KL06jR713Y0BlK5ywXqn4cIel/I64BbPwlv9tAPAvJlDBq9zpXoCMguuMHEVru+Q4Zh9W3Hab8yK9/Ke4gWDwezUkE5u1ktFitdC/UIL+EvXXcCKwL0VMNFyqf4m/b3CXiDvtd9uoUwsS9YoFn6NHgR2LrIbiSexEL84vvF3iGr+9rnYjIhbBYhCs+zYJ8JghVvIWAR1xG2mZ3VY+1oDV7FGlA8nhtrDtX725i7m7H7MMrMe67U6KcQB4UJf3wYV/+f0YhS4NQAQb73OLKZKA4r8PsTqH7OL3cI63Eo0O3laS/1hUhFDq2aNSjqKf3IGevuqfO+s6dyHTMJ/CMtZ9G26VyWWISzcpffTiHyb0O87mH644zPGGIPmPZ5KJfAKLcMnEALjqWrEgZAL/oHe2j4pCJedXQHC4iDsfHzycVACxmR2jZjigzX1QlY=
    - secure: TKgVg3BKN/SPULu/CB1USa7WiGKYDNZN3Q1DoDk+lNENNmf1eKxieMmLOEWNSDW5cmqL40voQsT/wMhgZ99zxhIk385KCpVHT4l8z8r7IlB1lZP4BAld57l+oflB65clBHXWDuQGSyGw2CJuP4sNenlrIkGbmWx86JeN+P4JkcbIqgS3x9UQ1BsRpKBteKHIdwB7jKRq6XhYpw73VB2dquP18ABHtUUXXQ9jIm4QLtW7e5Lroyv9TD1m/AHmLquCnz14KA2gP2N0ZKfJ6eVyg8aK+B0eiHu5kpy1QHAVHFbYLf3YsP82SllWf4bPUFhGMN2dtURE/sZNhMTemyFgiPRZu7KgTIQRGM6UIBKbKzdAEUYIIfushZZFblSGLcx3Rqw1Cc8MRD4jhNbsnoCqAlBTsYU4Y5OptsF4NY9Rw7eqSpvSI9cjqtJH/6OAubcojbdOudtobRM+VQDI/mAKmP9e09hz5V4KmniZg7KeJx0ysTQAhIDF6WfOPWOSDnSm6ljKoXwwtUBwtY9lZu6SnrMGg03AGlhrixF7tD/zOS+Q0jBw3D8Sk4cRMwW7ZS9R3EsW3/8rn/h9zNPbign7jqPnESPpj89LvlTqaoCXPqqlbBFIq3eILf+uivcB6cfTi2vd6R5gwfjwn5seBrp/ijl/JM6cfPCuTNI4Ni5NnKQ=

install:
  - npm ci

script: npm run prettify-check &&
  npm run lint &&
  npm run test

after_success:
  - docker build -t tomasbalt/dcu_project_search_backend:latest .
  - echo "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_ID"
  - docker push tomasbalt/dcu_project_search_backend
